### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by culmat** [BaselHack/baselhack.ch#13]
Setup instructions for the development environment.
How to get up and running?
https://laravel.com/docs/5.6/homestead ?
What to clone where. Any suggestions for an IDE?
I have Ubuntu and no recent PHP experience.
Maybe use the wiki for this?

**Comment by StanBarrows** [comment]
Update How To Contribute:
https://github.com/BaselHack/baselhack.ch/wiki/How-To-Contribute
