### ISSUE TITLE
Metadata for website

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/baselhack.ch#9]
Hallo Jutta

Für jede Seite von baselhack.ch benötigen wir MetaDaten:

**MetaDaten Umfang:**
Page Title (Up To 60 Chars)
Page Description (Up To 160 Chars)
Keywords (About 10 per page)

**Aktuell Seiten**
- Start page
- Imprint page
- Privacy page
- Log-In page for Members

Liebe Gruess
Sebastian

**Comment by jjerlich** [comment]
MetaDaten: Index Baselhack:
Page Title (BaselHack - More than a Hack) Up To 60 Chars
Page Description (BaselHack is more than a Hackathon –  we connect people, take fun seriously and grow open innovation) - Up To 160 Chars
Keywords (BaselHack, Hackathon, connect, talents, serious fun, open innovation, Basel Stadt, Basel Land, Jura, Dreiländereck) About 10 per page
