### ISSUE TITLE
Duplicate participants?

### ISSUE THREAD

**Issue by culmat** [BaselHack/baselhack.ch#96]
Help avoiding duplicate registrations.
It seems to me that participant 13 and 112 as well as 114 and 35 are the same person.
The first and last name are the same, email is different. The names are not common ( Thomas Müller type).

**Possible solution**
on subscription, if name already exists, display message
'We already have an account with your name and the email address mxxxhxxx.xxxmxxx@gmail.com. Is this you?' 
(blank out 75% of the email)

**Comment by StanBarrows** [comment]
Two duplicates out of 150 people inside the database seems for me oukey (1.3%). Its also a no go in terms of data privacy and security to show any output or message about registered user.

My approach woul be to have the possibility to merge accounts or allow multiple emails.
